title: Tadej's Notes
name: "Tadej's Notes"
author: Tadej Svetina
baseurl: ""
description: My learning notes, more for myself than anything else.
profile_url: "http://tadejsv.github.io"
include: ['_pages']

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-katex
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
